FROM  tomcat:8.5-jre8

ADD war-1.0-SNAPSHOT.war  /usr/local/tomcat/webapps/ws.war

#-e mongo.host=192.168.1.136 -e mongo.userName=tws -e mongo.userPassword=tws -e mongo.dbName=tws -e facebook.clientID=945042745623634 -e facebook.clientSecret=711e9c36ba8ec834d5facbfbe947b41b -e textEncryption.password=xxx -e textEncryption.salt=yyy